# Generated by Django 5.0.7 on 2024-10-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
